### ISSUE TITLE
2022 leaderboard is incorrect

### ISSUE THREAD

**Issue by morgoth1145** [fuglede/aoc-full-leaderboard#1]
I was looking at this and noticed it listed me as 32nd in 2022 which isn't correct, I was 34th. Were some days missed or something? My score is accurate but some others near the top are not accurate and undercount their scores.
I haven't audited other years.

**Comment by fuglede** [comment]
Whoops, good catch, thanks! While playing around with what the leaderboards looked like during the month, I had accidentally dropped the 25th of each year.
